name: Preview

on:
  pull_request:
    branches:
      - main

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - uses: pulumi/actions@v6
        with:
          command: preview
          stack-name: holochain/github
          comment-on-pr: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}